app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage_view),
    path('about/', views.about_view),
    
    path('weather/', include('weather.urls'))
]

app/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather_view, name='weather'),
    path('search/', views.search_weather_view, name='search-weather'),
]

app/weather/models.py
from django.db import models

# Create your models here.

app/app/views.py
# views.py
from django.shortcuts import render

def homepage_view(request):
    return render(request, 'homepage.html')

def about_view(request):
    return render(request, 'about.html')

app/weather/views.py
from django.shortcuts import render
from . import weather_api
from icecream import ic

import logging

# Create your views here.
def weather_view(request) -> render:
    logging.info('Calling weather_view')
    forecast = weather_api.fetch()
    daily_forecasts = extract_daily_forecasts(forecast['daily_forecasts'])
    logging.debug(f'Daily Forecasts: {daily_forecasts}')
    today_hourly_forecasts = extract_hourly_forecasts(daily_forecasts[0]['hourly_forecasts']) # daily_forecasts[0] is today's forecast
    ic(daily_forecasts[0]['hourly_forecasts'])
    ic(today_hourly_forecasts)
    
    logging.info('Redirecting to weather/weather.html')
    return render(
        request, 
        'weather/weather.html', 
        {
            'forecast': forecast,
            'daily_forecasts': daily_forecasts,
            'today_hourly_forecasts': today_hourly_forecasts,
        })
    
def search_weather_view(request) -> render:
    logging.info('Calling search_weather_view')
    location: str = request.GET.get('location')
    if locationNotValid(location):
        return render(
            request, 
            'weather/search_weather.html', 
            {
                'success': False
                })
    try:
        forecast = weather_api.fetch(city_name=location)
    except Exception as e:
        logging.error(f'Error fetching weather for {location}: {e}')
        return render(
            request, 
            'weather/search_weather.html', 
            {
                'success': False
                })
        
    daily_forecasts = extract_daily_forecasts(forecast['daily_forecasts'])
    logging.debug(f'Daily Forecasts: {daily_forecasts}')
    today_hourly_forecasts = extract_hourly_forecasts(daily_forecasts[0]['hourly_forecasts']) # daily_forecasts[0] is today's forecast
    ic(daily_forecasts[0]['hourly_forecasts'])
    ic(today_hourly_forecasts)
    
    logging.info('Redirecting to weather/search_weather.html')
    return render(
        request, 
        'weather/search_weather.html',
        {
            'success': True,
            'forecast': forecast,
            'daily_forecasts': daily_forecasts,
            'today_hourly_forecasts': today_hourly_forecasts,
        })
    

def locationNotValid(location) -> bool:
    return location is None or len(location) == 0

    
'''
    Extracts the daily forecasts as list of dictionaries from the generator
'''
def extract_daily_forecasts(daily_forecasts) -> list:
    result = [
        {
            'date': daily_forecast.date.strftime('%d-%m'),
            'lowest_temperature': daily_forecast.lowest_temperature,
            'highest_temperature': daily_forecast.highest_temperature,
            'sunrise': daily_forecast.sunrise.strftime('%H:%M'),
            'sunset': daily_forecast.sunset.strftime('%H:%M'),
            'temperature_unit': daily_forecast.unit.temperature, 
            'hourly_forecasts': daily_forecast.hourly_forecasts,
        } 
        for daily_forecast in daily_forecasts]

    
    return result


def extract_hourly_forecasts(hourly_forecasts) -> list:
    result = [
        {
            'kind': hourly_forecast.kind,
            'humidity': hourly_forecast.humidity,
            'precipitation': hourly_forecast.precipitation,
            'temperature': hourly_forecast.temperature,
            'pressure': hourly_forecast.pressure,
            'time': hourly_forecast.time.strftime('%H:%M'),
            'chances_of_rain': hourly_forecast.chances_of_rain,
            'wind_speed': hourly_forecast.wind_speed,
            'wind_direction': hourly_forecast.wind_direction,
            'visibility': hourly_forecast.visibility,
            'temperature_unit': hourly_forecast.unit.temperature,
            'pressure_unit': hourly_forecast.unit.pressure,
            'velocity_unit': hourly_forecast.unit.velocity,
            'visibility_unit': hourly_forecast.unit.visibility,
            'precipitation_unit': hourly_forecast.unit.precipitation,
            
        }
        for hourly_forecast in hourly_forecasts
    ]
    
    return result

app/templates/about.html
<!--home.html-->
{% extends 'layout.html'%}
{% block title%}
    About Me
{% endblock %}
{% block content %}
<!-- About 1 - Bootstrap Brain Component -->
<section class="py-4 py-md-5 min-vh-100">
  <div class="container border border-secondary bg-light rounded p-2">
    <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
      <div class="col-12 col-lg-6 col-xl-5">
        <img class="img-fluid img-thumbnail" loading="lazy" src="https://raw.githubusercontent.com/AleandroPresta/articles-webapp/main/app/static/assets/Io.jpeg" alt="My picture">
      </div>
      <div class="col-12 col-lg-6 col-xl-7">
        <div class="row justify-content-xl-center">
          <div class="col-12 col-xl-11">
            <h2 class="mb-3">Who Am I?</h2>
            <p class="lead fs-4 text-secondary mb-3">I'm Aleandro Presta, a Software Engineer specialized in Machine Learning and Web Development</p>
            <p class="mb-5">I am a dedicated and enthusiastic software engineer with a master's degree in Artificial Intelligence and Machine Learning. My passion for technology extends beyond my professional career, as I continuously seek to expand my knowledge and skills in the ever-evolving field of software development.</p>
            <div class="row gy-4 gy-md-0 gx-xxl-5X">
              <div class="col-12 col-md-6">
                <h3 align="left">Connect with me:</h3>
                <p align="left">
                <a href="https://linkedin.com/in/aleandro-presta-6523471b9" target="blank" title="My LinkedIn profile"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="aleandro-presta-6523471b9" height="30" width="40" /></a>
                <a href="https://github.com/AleandroPresta" target="blank" title="My GitHub profile"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/github.svg" alt="AleandroPresta" height="30" width="40" /></a>
                <a href="mailto: aleandro.presta@outlook.com" target="blank" title="Send me an Email"><img align="center" src="https://raw.githubusercontent.com/AleandroPresta/articles-webapp/main/app/static/assets/envelope.svg" alt="Email" height="30" width="40" /></a>
                <a href="https://www.frontendmentor.io/profile/AleandroPresta" target="blank" title="My Frontend Mentor profile"><img align="center" src="https://cdn.worldvectorlogo.com/logos/frontendmentor-logo.svg" alt="Email" height="30" width="40" /></a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/homepage.html
{% extends 'layout.html'%}
{% block title%}
    Homepage
{% endblock %}
{% block content %}
    <div id="intro" class="bg-image">
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
            <div class="container d-flex align-items-center justify-content-center text-center h-100">
                <div class="text-white" data-mdb-theme="dark">
                    <h1 class="mb-3">Weather App</h1>
                    <h5 class="mb-4">Search Weather Forecast</h5>
                    <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" method="GET" action="{% url 'weather:search-weather' %}">
                        <div class="input-group">
                            <div class="form-outline">
                                {% csrf_token %}
                                <input id="search-focus" type="search" id="form1" class="form-control" placeholder="Search..." name="location"/>
                            </div>
                            <button type="submit" class="btn btn-dark">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
        Weather App
    {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    <!-- Navigation -->
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="{% static "assets/nav-icon.avif" %}" alt="Bootstrap" width="32" height="32" class="rounded">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="/" class="nav-link px-2 text-white">Home</a></li>
                    <li><a href="/about" class="nav-link px-2 text-white">About</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" method="GET" action="{% url 'weather:search-weather' %}">
                    <div class="input-group">
                        <div class="form-outline">
                            {% csrf_token %}
                            <input id="search-focus" type="search" id="form1" class="form-control" placeholder="Search..." name="location"/>
                        </div>
                        <button type="submit" class="btn btn-dark">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/9b4fbdae70.js" crossorigin="anonymous"></script>
</body>
</html>

app/weather/templates/weather/search_weather.html
{% extends 'layout.html' %}
{% block title %}
    Weather Today in {{ forecast.location }}, {{ forecast.region }}, {{ forecast.country }}
{% endblock %}
{% block content %}
{% if success %}
<div class="container center">
    <div class="row d-flex justify-content-center align-items-center my-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Weather Today in {{ forecast.location }}, {{ forecast.region }}, {{ forecast.country }}</h5>
                    <div class="container card-text">
                        <div class="row">
                            <p>Feels like</p>
                            <h1>{{ forecast.feels_like }}˚ {{ forecast.temperature_unit }}</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m-2">
                            <table class="table">
                                <thead></thead>
                                <tbody>
                                    <tr class="row">
                                        <th scope="row"></th>
                                        <td>{{ forecast.kind.emoji }} Weather: {{ forecast.kind }}</td>
                                        <td><i class="fa-solid fa-droplet"></i> Humidity: {{ forecast.humidity }} %</td>
                                        <td><i class="fa-solid fa-ruler"></i> Pressure: {{ forecast.pressure }} {{ forecast.pressure_unit }}</td>
                                        <td><i class="fa-solid fa-umbrella"></i> Precipitation: {{ forecast.precipitation }} {{ forecast.precipitation_unit }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col m-2">
                            <table class="table">
                                <thead></thead>
                                <tbody>
                                    <tr class="row">
                                        <td><i class="fa-solid fa-location-arrow"></i> Wind Direction: {{ forecast.wind_direction }}</td>
                                        <td><i class="fa-solid fa-wind"></i> Wind Speed: {{ forecast.wind_speed }} {{ forecast.velocity_unit }}</td>
                                        <td><i class="fa-solid fa-eye"></i> Visibility: {{ forecast.visibility }} {{ forecast.visibility_unit }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div> <!-- Close second row -->
                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center align-items-center mb-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Daily Weather:</h5>
                    <div class="container card-text">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="col">Date</th>
                                    <th class="col">Lowest Temperature</th>
                                    <th class="col">Highest Temperature</th>
                                    <th class="col">Sunrise</th>
                                    <th class="col">Sunset</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for daily_forecast in daily_forecasts %}
                                    <tr>
                                        <td>{{ daily_forecast.date }}</td>
                                        <td>{{ daily_forecast.lowest_temperature }}˚ {{ daily_forecast.temperature_unit }}</td>
                                        <td>{{ daily_forecast.highest_temperature }}˚ {{ daily_forecast.temperature_unit }}</td>
                                        <td>{{ daily_forecast.sunrise }}</td>
                                        <td>{{ daily_forecast.sunset }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center align-items-center mb-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Today's Weather:</h5>
                    <div class="container card-text">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="col">Time</th>
                                    <th class="col">Kind</th>
                                    <th class="col">Temperature</th>
                                    <th class="col">Chances of Rain</th>
                                    <th class="col">Wind Speed</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for hourly_forecast in today_hourly_forecasts %}
                                    <tr>
                                        <td>{{ hourly_forecast.time }}</td>
                                        <td>{{ hourly_forecast.kind.emoji }}</td>
                                        <td>{{ hourly_forecast.temperature }}° {{ hourly_forecast.temperature_unit}} </td>
                                        <td>{{ hourly_forecast.chances_of_rain }}%</td>
                                        <td>{{ hourly_forecast.wind_speed }} {{ hourly_forecast.velocity_unit }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container center">
    <div class="row d-flex justify-content-center align-items-center my-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <h1 class="m-5 text-center">Location not found</h1>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

app/weather/templates/weather/weather.html
{% extends 'layout.html' %}
{% block title %}
    Weather
{% endblock %}
{% block content %}
<div class="container center">
    <div class="row d-flex justify-content-center align-items-center my-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Weather Today in {{ forecast.location }}, {{ forecast.region }}, {{ forecast.country }}</h5>
                    <div class="container card-text">
                        <div class="row">
                            <p>Feels like</p>
                            <h1>{{ forecast.feels_like }}˚ {{ forecast.temperature_unit }}</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m-2">
                            <table class="table">
                                <thead></thead>
                                <tbody>
                                    <tr class="row">
                                        <th scope="row"></th>
                                        <td>{{ forecast.kind.emoji }} Weather: {{ forecast.kind }}</td>
                                        <td><i class="fa-solid fa-droplet"></i> Humidity: {{ forecast.humidity }} %</td>
                                        <td><i class="fa-solid fa-ruler"></i> Pressure: {{ forecast.pressure }} {{ forecast.pressure_unit }}</td>
                                        <td><i class="fa-solid fa-umbrella"></i> Precipitation: {{ forecast.precipitation }} {{ forecast.precipitation_unit }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col m-2">
                            <table class="table">
                                <thead></thead>
                                <tbody>
                                    <tr class="row">
                                        <td><i class="fa-solid fa-location-arrow"></i> Wind Direction: {{ forecast.wind_direction }}</td>
                                        <td><i class="fa-solid fa-wind"></i> Wind Speed: {{ forecast.wind_speed }} {{ forecast.velocity_unit }}</td>
                                        <td><i class="fa-solid fa-eye"></i> Visibility: {{ forecast.visibility }} {{ forecast.visibility_unit }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div> <!-- Close second row -->
                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center align-items-center mb-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Daily Weather:</h5>
                    <div class="container card-text">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="col">Date</th>
                                    <th class="col">Lowest Temperature</th>
                                    <th class="col">Highest Temperature</th>
                                    <th class="col">Sunrise</th>
                                    <th class="col">Sunset</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for daily_forecast in daily_forecasts %}
                                    <tr>
                                        <td>{{ daily_forecast.date }}</td>
                                        <td>{{ daily_forecast.lowest_temperature }}˚ {{ daily_forecast.temperature_unit }}</td>
                                        <td>{{ daily_forecast.highest_temperature }}˚ {{ daily_forecast.temperature_unit }}</td>
                                        <td>{{ daily_forecast.sunrise }}</td>
                                        <td>{{ daily_forecast.sunset }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center align-items-center mb-2">
        <div class="col-sm-fluid col-md-10 col-lg-8 col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Today's Weather:</h5>
                    <div class="container card-text">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="col">Time</th>
                                    <th class="col">Kind</th>
                                    <th class="col">Temperature</th>
                                    <th class="col">Chances of Rain</th>
                                    <th class="col">Wind Speed</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for hourly_forecast in today_hourly_forecasts %}
                                    <tr>
                                        <td>{{ hourly_forecast.time }}</td>
                                        <td>{{ hourly_forecast.kind.emoji }}</td>
                                        <td>{{ hourly_forecast.temperature }}° {{ hourly_forecast.temperature_unit}} </td>
                                        <td>{{ hourly_forecast.chances_of_rain }}%</td>
                                        <td>{{ hourly_forecast.wind_speed }} {{ hourly_forecast.velocity_unit }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}